panda:
  torque_bias:
    - -0.0 # joint 1
    - -0.0 # joint 2
    - -0.1 # joint 3
    - 0.0 # joint 4
    - 0.0 # joint 5
    - 0.0 # joint 6
    - 0.0 # joint 7
  torque_stiction:
    - 0.5 # joint 1
    - 0.55 # joint 2
    - 0.35 # joint 3
    - 0.43 # joint 4
    - 0.32 # joint 5
    - 0.35 # joint 6
    - 0.2 # joint 7
