panda:
  torque_bias:
    - 0.0 # joint 1
    - -0.15 # joint 2
    - 0.15 # joint 3
    - 0.2 # joint 4
    - 0.0 # joint 5
    - 0.10 # joint 6
    - 0.0 # joint 7
  torque_stiction:
    - 0.60 # joint 1
    - 0.60 # joint 2
    - 0.45 # joint 3
    - 0.33 # joint 4
    - 0.64 # joint 5
    - 0.30 # joint 6
    - 0.2 # joint 7
  name: 'panda-4'
